### ISSUE TITLE
is it possible to add 'pseudo 3d' for render or how to create custom charts?

### ISSUE THREAD

**Issue by plandem** [antvis/feedback#15]
I know that G2 is language, but sometimes we need chart - like 3d funnel, or 3d pyramid. or custom version of gauge. How to do it?

E.g.:
http://www.fusioncharts.com/charts/funnel-charts/
http://www.fusioncharts.com/charts/gauges/

What do i need to do?

**Comment by TomHuangCN** [comment]
we can't do it util our 3D Render Engine finish

**Comment by dxq613** [comment]
The current version of the G2 supports only 2D graphics, custom Shape features planned for the next version released around July.
But the pseudo 3D effect is only in the data visualization on the visual effects, the need for further discussion.

**Comment by plandem** [comment]
I see about custom shapes - looking forward for it. about 3d engine - what kind of discussion do you need?

**Comment by dxq613** [comment]
We know that visualization is mapping data and visual channels, we usually say 3D, 2D position are used to distinguish between different data, and pseudo-3D only  increase  visual effects, we believe that the priority is not too high.

We plan to develop 3d renderer mainly to add a dimension of impression data, rather than considering visual aspects.
